const WORDS = [
  // ── Greetings (15) ──
  { en: "hello / goodbye",              th: "sawadee",                  cat: "greetings" },
  { en: "thank you",                    th: "khob khun",                cat: "greetings" },
  { en: "you're welcome / no problem",  th: "mai pen rai",              cat: "greetings" },
  { en: "sorry / excuse me",            th: "kho thot",                 cat: "greetings" },
  { en: "yes",                          th: "chai",                     cat: "greetings", note: "also used as a polite confirmation particle" },
  { en: "no",                           th: "mai chai",                 cat: "greetings", note: "mai = negation prefix; mai chai = 'not yes'" },
  { en: "please",                       th: "garuuna",                  cat: "greetings" },
  { en: "how are you?",                 th: "sabai dee mai",            cat: "greetings" },
  { en: "I'm fine",                     th: "sabai dee",                cat: "greetings" },
  { en: "nice to meet you",             th: "yin dee tee dai roo jak",  cat: "greetings" },
  { en: "good luck",                    th: "chok dee",                 cat: "greetings" },
  { en: "cheers!",                      th: "chon gaew",                cat: "greetings" },
  { en: "see you later",                th: "laew phob gan mai",        cat: "greetings" },
  { en: "good night",                   th: "ratree sawat",             cat: "greetings" },
  { en: "I don't understand",           th: "mai khao jai",             cat: "greetings" },

  // ── Numbers (25) ──
  { en: "zero",                         th: "soon",                     cat: "numbers", num: "0" },
  { en: "one",                          th: "neung",                    cat: "numbers", num: "1" },
  { en: "two",                          th: "song",                     cat: "numbers", num: "2" },
  { en: "three",                        th: "sam",                      cat: "numbers", num: "3" },
  { en: "four",                         th: "see",                      cat: "numbers", num: "4" },
  { en: "five",                         th: "ha",                       cat: "numbers", num: "5" },
  { en: "six",                          th: "hok",                      cat: "numbers", num: "6" },
  { en: "seven",                        th: "jet",                      cat: "numbers", num: "7" },
  { en: "eight",                        th: "paet",                     cat: "numbers", num: "8" },
  { en: "nine",                         th: "gao",                      cat: "numbers", num: "9" },
  { en: "ten",                          th: "sip",                      cat: "numbers", num: "10" },
  { en: "eleven",                       th: "sip-et",                   cat: "numbers", num: "11" },
  { en: "twelve",                       th: "sip-song",                 cat: "numbers", num: "12" },
  { en: "fifteen",                      th: "sip-ha",                   cat: "numbers", num: "15" },
  { en: "twenty",                       th: "yee-sip",                  cat: "numbers", num: "20" },
  { en: "twenty-one",                   th: "yee-sip-et",               cat: "numbers", num: "21" },
  { en: "thirty",                       th: "sam-sip",                  cat: "numbers", num: "30" },
  { en: "forty",                        th: "see-sip",                  cat: "numbers", num: "40" },
  { en: "fifty",                        th: "ha-sip",                   cat: "numbers", num: "50" },
  { en: "one hundred",                  th: "roi",                      cat: "numbers", num: "100" },
  { en: "two hundred",                  th: "song roi",                 cat: "numbers", num: "200" },
  { en: "one thousand",                 th: "phan",                     cat: "numbers", num: "1,000" },
  { en: "ten thousand",                 th: "meun",                     cat: "numbers", num: "10,000" },
  { en: "one hundred thousand",         th: "saen",                     cat: "numbers", num: "100,000" },
  { en: "one million",                  th: "lan",                      cat: "numbers", num: "1,000,000" },

  // ── Colors (12) ──
  { en: "red",                          th: "sii daeng",                cat: "colors" },
  { en: "blue",                         th: "sii fah",                  cat: "colors" },
  { en: "green",                        th: "sii khiao",                cat: "colors" },
  { en: "yellow",                       th: "sii leuang",               cat: "colors" },
  { en: "black",                        th: "sii dam",                  cat: "colors" },
  { en: "white",                        th: "sii khao",                 cat: "colors" },
  { en: "pink",                         th: "sii chompoo",              cat: "colors" },
  { en: "orange",                       th: "sii som",                  cat: "colors" },
  { en: "purple",                       th: "sii muang",                cat: "colors" },
  { en: "brown",                        th: "sii nam tan",              cat: "colors" },
  { en: "grey",                         th: "sii thao",                 cat: "colors" },
  { en: "gold",                         th: "sii thong",                cat: "colors" },

  // ── Food (55) ──
  { en: "delicious",                    th: "aroy",                     cat: "food" },
  { en: "spicy",                        th: "pet",                      cat: "food", note: "same romanization as 'duck' (pet) — tone differs" },
  { en: "not spicy",                    th: "mai pet",                  cat: "food" },
  { en: "sweet",                        th: "wan",                      cat: "food" },
  { en: "sour",                         th: "priao",                    cat: "food" },
  { en: "salty",                        th: "khem",                     cat: "food" },
  { en: "bitter",                       th: "khom",                     cat: "food" },
  { en: "rice",                         th: "khao",                     cat: "food", note: "also: white (color), enter (verb) — tones differ" },
  { en: "sticky rice",                  th: "khao niao",                cat: "food" },
  { en: "fried rice",                   th: "khao pad",                 cat: "food" },
  { en: "noodles",                      th: "gway teow",                cat: "food" },
  { en: "pad thai",                     th: "pad thai",                 cat: "food" },
  { en: "tom yum soup",                 th: "tom yum",                  cat: "food" },
  { en: "green curry",                  th: "gaeng khiao wan",          cat: "food" },
  { en: "red curry",                    th: "gaeng daeng",              cat: "food" },
  { en: "papaya salad",                 th: "som tam",                  cat: "food" },
  { en: "mango sticky rice",            th: "khao niao mamuang",        cat: "food" },
  { en: "spring rolls",                 th: "poh pia",                  cat: "food" },
  { en: "satay",                        th: "satay",                    cat: "food" },
  { en: "chicken",                      th: "gai",                      cat: "food" },
  { en: "pork",                         th: "moo",                      cat: "food" },
  { en: "beef",                         th: "nuea",                     cat: "food" },
  { en: "fish",                         th: "pla",                      cat: "food" },
  { en: "shrimp",                       th: "goong",                    cat: "food" },
  { en: "crab",                         th: "poo",                      cat: "food" },
  { en: "squid",                        th: "pla muek",                 cat: "food" },
  { en: "egg",                          th: "khai",                     cat: "food" },
  { en: "tofu",                         th: "tao hoo",                  cat: "food" },
  { en: "vegetables",                   th: "phak",                     cat: "food" },
  { en: "garlic",                       th: "gratiam",                  cat: "food" },
  { en: "onion",                        th: "hua hom",                  cat: "food" },
  { en: "chili",                        th: "phrik",                    cat: "food" },
  { en: "ginger",                       th: "khing",                    cat: "food" },
  { en: "lemongrass",                   th: "ta krai",                  cat: "food" },
  { en: "coconut milk",                 th: "ga ti",                    cat: "food" },
  { en: "fish sauce",                   th: "nam pla",                  cat: "food" },
  { en: "soy sauce",                    th: "see-ew",                   cat: "food" },
  { en: "sugar",                        th: "nam tan",                  cat: "food", note: "literally 'palm water'; nam tan also = brown (sii nam tan)" },
  { en: "salt",                         th: "gleua",                    cat: "food" },
  { en: "lime",                         th: "manao",                    cat: "food" },
  { en: "mango",                        th: "mamuang",                  cat: "food" },
  { en: "banana",                       th: "gluai",                    cat: "food" },
  { en: "pineapple",                    th: "sapparot",                 cat: "food" },
  { en: "watermelon",                   th: "taeng mo",                 cat: "food" },
  { en: "durian",                       th: "thurian",                  cat: "food" },
  { en: "coconut",                      th: "maprao",                   cat: "food" },
  { en: "bread",                        th: "khanom pang",              cat: "food" },
  { en: "soup",                         th: "gaeng / tom",              cat: "food" },
  { en: "stir-fried",                   th: "pad",                      cat: "food", note: "cooking method prefix, e.g. pad thai, pad kra pao" },
  { en: "deep-fried",                   th: "thot",                     cat: "food" },
  { en: "steamed",                      th: "neung",                    cat: "food", note: "same romanization as 'one' (neung) — tone differs" },
  { en: "grilled",                      th: "ping / yang",              cat: "food" },
  { en: "fried egg",                    th: "khai dao",                 cat: "food" },
  { en: "omelette",                     th: "khai jeow",                cat: "food" },
  { en: "papaya",                       th: "malakaw",                  cat: "food" },

  // ── Drinks (10) ──
  { en: "water",                        th: "nam",                      cat: "drinks" },
  { en: "coffee",                       th: "gafae",                    cat: "drinks" },
  { en: "tea",                          th: "cha",                      cat: "drinks" },
  { en: "beer",                         th: "bia",                      cat: "drinks" },
  { en: "wine",                         th: "wayn",                     cat: "drinks" },
  { en: "juice",                        th: "nam phon lamai",           cat: "drinks" },
  { en: "coconut water",                th: "nam maprao",               cat: "drinks" },
  { en: "soda",                         th: "nam at lom",               cat: "drinks" },
  { en: "milk",                         th: "nom",                      cat: "drinks" },
  { en: "ice",                          th: "nam khaeng",               cat: "drinks" },

  // ── Family (15) ──
  { en: "father",                       th: "pho",                      cat: "family" },
  { en: "mother",                       th: "mae",                      cat: "family" },
  { en: "older sibling",                th: "phi",                      cat: "family" },
  { en: "younger sibling",              th: "nong",                     cat: "family" },
  { en: "husband",                      th: "pua",                      cat: "family" },
  { en: "wife",                         th: "mia",                      cat: "family" },
  { en: "son",                          th: "luk chai",                 cat: "family" },
  { en: "daughter",                     th: "luk sao",                  cat: "family" },
  { en: "grandfather",                  th: "poo / ta",                 cat: "family" },
  { en: "grandmother",                  th: "ya / yai",                 cat: "family" },
  { en: "uncle",                        th: "lung / na",                cat: "family" },
  { en: "aunt",                         th: "pa / na",                  cat: "family" },
  { en: "friend",                       th: "pheuan",                   cat: "family" },
  { en: "neighbor",                     th: "pheuan ban",               cat: "family" },
  { en: "child",                        th: "dek / luk",                cat: "family" },

  // ── Body (20) ──
  { en: "head",                         th: "hua",                      cat: "body" },
  { en: "face",                         th: "na",                       cat: "body" },
  { en: "eye",                          th: "ta",                       cat: "body" },
  { en: "ear",                          th: "hoo",                      cat: "body" },
  { en: "nose",                         th: "jamook",                   cat: "body" },
  { en: "mouth",                        th: "pak",                      cat: "body" },
  { en: "tooth",                        th: "fan",                      cat: "body" },
  { en: "hair",                         th: "phom",                     cat: "body" },
  { en: "neck",                         th: "kor",                      cat: "body" },
  { en: "shoulder",                     th: "lai",                      cat: "body" },
  { en: "arm",                          th: "khaen",                    cat: "body" },
  { en: "hand",                         th: "meu",                      cat: "body" },
  { en: "finger",                       th: "niu",                      cat: "body" },
  { en: "chest",                        th: "ok",                       cat: "body" },
  { en: "stomach",                      th: "thong",                    cat: "body" },
  { en: "back",                         th: "lang",                     cat: "body" },
  { en: "leg",                          th: "kha",                      cat: "body" },
  { en: "knee",                         th: "hua khao",                 cat: "body" },
  { en: "foot",                         th: "tao",                      cat: "body" },
  { en: "heart",                        th: "hua jai",                  cat: "body" },

  // ── Clothing (15) ──
  { en: "shirt",                        th: "seua",                     cat: "clothing" },
  { en: "trousers / pants",             th: "gang-geng",                cat: "clothing" },
  { en: "dress",                        th: "seua phah",                cat: "clothing" },
  { en: "skirt",                        th: "gra-prong",                cat: "clothing" },
  { en: "shoes",                        th: "rong thao",                cat: "clothing" },
  { en: "sandals",                      th: "rong thao taem",           cat: "clothing" },
  { en: "hat",                          th: "muat",                     cat: "clothing" },
  { en: "glasses",                      th: "waen ta",                  cat: "clothing" },
  { en: "bag",                          th: "gra-pao",                  cat: "clothing" },
  { en: "watch",                        th: "na li ga",                 cat: "clothing" },
  { en: "ring",                         th: "waen",                     cat: "clothing" },
  { en: "necklace",                     th: "soy kor",                  cat: "clothing" },
  { en: "clothes",                      th: "seua pha",                 cat: "clothing" },
  { en: "jacket / coat",                th: "seua klum",                cat: "clothing" },
  { en: "underwear",                    th: "gang-geng nai",            cat: "clothing" },

  // ── Animals (20) ──
  { en: "dog",                          th: "maa (falling tone)",       cat: "animals", note: "falling tone; same syllable as horse (rising) and come (mid)" },
  { en: "cat",                          th: "maew",                     cat: "animals" },
  { en: "elephant",                     th: "chang",                    cat: "animals", note: "classifier for elephants; chang also means 'carpenter'" },
  { en: "monkey",                       th: "ling",                     cat: "animals" },
  { en: "bird",                         th: "nok",                      cat: "animals", note: "classifier for birds; also means 'outside' in some contexts" },
  { en: "snake",                        th: "ngu",                      cat: "animals" },
  { en: "tiger",                        th: "seua",                     cat: "animals", note: "same romanization as shirt (seua) — tones differ" },
  { en: "horse",                        th: "maa (rising tone)",        cat: "animals", note: "rising tone; same syllable as dog (falling) and come (mid)" },
  { en: "cow",                          th: "wua",                      cat: "animals", note: "classifier for cattle" },
  { en: "pig",                          th: "moo",                      cat: "animals", note: "also means pork (food); same word" },
  { en: "duck",                         th: "pet",                      cat: "animals", note: "same romanization as spicy (pet) — tones differ" },
  { en: "rabbit",                       th: "gra-tai",                  cat: "animals" },
  { en: "frog",                         th: "gob",                      cat: "animals" },
  { en: "mosquito",                     th: "yung",                     cat: "animals" },
  { en: "ant",                          th: "mot",                      cat: "animals" },
  { en: "butterfly",                    th: "phi seua",                 cat: "animals" },
  { en: "crocodile",                    th: "jaw-ra-khe",               cat: "animals" },
  { en: "fish",                         th: "pla",                      cat: "animals", note: "same word as fish (food)" },
  { en: "chicken (animal)",             th: "gai",                      cat: "animals", note: "same word as chicken (food); also classifier for chickens" },
  { en: "buffalo",                      th: "khwai",                    cat: "animals" },

  // ── Nature (15) ──
  { en: "sun",                          th: "pra-a-tit",                cat: "nature" },
  { en: "moon",                         th: "pra-jan",                  cat: "nature" },
  { en: "star",                         th: "dao",                      cat: "nature" },
  { en: "sky",                          th: "fa",                       cat: "nature" },
  { en: "cloud",                        th: "mek",                      cat: "nature" },
  { en: "rain",                         th: "fon",                      cat: "nature" },
  { en: "wind",                         th: "lom",                      cat: "nature" },
  { en: "mountain",                     th: "phu-khao",                 cat: "nature" },
  { en: "river",                        th: "mae-nam",                  cat: "nature" },
  { en: "sea / ocean",                  th: "ta-le",                    cat: "nature" },
  { en: "beach",                        th: "hat",                      cat: "nature" },
  { en: "island",                       th: "ko",                       cat: "nature" },
  { en: "tree",                         th: "ton mai",                  cat: "nature" },
  { en: "flower",                       th: "dok mai",                  cat: "nature" },
  { en: "grass",                        th: "ya",                       cat: "nature" },

  // ── Weather (10) ──
  { en: "hot (weather)",                th: "rorn",                     cat: "weather" },
  { en: "cold (weather)",               th: "nao",                      cat: "weather" },
  { en: "cool",                         th: "yen",                      cat: "weather" },
  { en: "it's raining",                 th: "fon tok",                  cat: "weather" },
  { en: "sunny",                        th: "daet ork",                 cat: "weather" },
  { en: "cloudy",                       th: "fa mit",                   cat: "weather" },
  { en: "windy",                        th: "lom paed",                 cat: "weather" },
  { en: "humid",                        th: "cheun",                    cat: "weather" },
  { en: "dry season",                   th: "na raeng",                 cat: "weather" },
  { en: "rainy season",                 th: "na fon",                   cat: "weather" },

  // ── Places (25) ──
  { en: "house / home",                 th: "ban",                      cat: "places" },
  { en: "hotel",                        th: "rong raem",                cat: "places" },
  { en: "hospital",                     th: "rong phayaban",            cat: "places" },
  { en: "school",                       th: "rong rian",                cat: "places" },
  { en: "university",                   th: "ma-ha-wi-tha-lai",         cat: "places" },
  { en: "office",                       th: "sam-nak-ngan",             cat: "places" },
  { en: "bank",                         th: "tha-na-khan",              cat: "places" },
  { en: "post office",                  th: "prai-sa-nee",              cat: "places" },
  { en: "police station",               th: "sa-than-ee tam-ruat",      cat: "places" },
  { en: "temple",                       th: "wat",                      cat: "places" },
  { en: "market",                       th: "ta-lat",                   cat: "places" },
  { en: "supermarket",                  th: "su-per-mar-ket",           cat: "places" },
  { en: "mall / department store",      th: "ha-sang",                  cat: "places" },
  { en: "restaurant",                   th: "raan a-han",               cat: "places" },
  { en: "café",                         th: "raan gafae",               cat: "places" },
  { en: "pharmacy",                     th: "raan khai ya",             cat: "places" },
  { en: "airport",                      th: "sa-naam-bin",              cat: "places" },
  { en: "train station",                th: "sa-than-ee rot fai",       cat: "places" },
  { en: "bus station",                  th: "sa-than-ee rot may",       cat: "places" },
  { en: "park",                         th: "su-uan sa-tha-ra-na",      cat: "places" },
  { en: "zoo",                          th: "su-uan sat",               cat: "places" },
  { en: "museum",                       th: "phi-phi-ta-phan",          cat: "places" },
  { en: "embassy",                      th: "sa-than-toot",             cat: "places" },
  { en: "border",                       th: "chai daen",                cat: "places" },
  { en: "island",                       th: "ko",                       cat: "places" },

  // ── Transport (12) ──
  { en: "car",                          th: "rot",                      cat: "transport" },
  { en: "motorbike",                    th: "rot mor-ter-sai",          cat: "transport" },
  { en: "bus",                          th: "rot may",                  cat: "transport" },
  { en: "train",                        th: "rot fai",                  cat: "transport" },
  { en: "taxi",                         th: "taxi",                     cat: "transport" },
  { en: "tuk-tuk",                      th: "tuk-tuk",                  cat: "transport" },
  { en: "boat",                         th: "reua",                     cat: "transport" },
  { en: "plane",                        th: "khreuang bin",             cat: "transport" },
  { en: "bicycle",                      th: "rot jak-gra-yaan",         cat: "transport" },
  { en: "subway / MRT",                 th: "rot fai tai din",          cat: "transport" },
  { en: "ticket",                       th: "tua",                      cat: "transport" },
  { en: "road / street",                th: "thanon",                   cat: "transport" },

  // ── Home (15) ──
  { en: "room",                         th: "hong",                     cat: "home" },
  { en: "bedroom",                      th: "hong norn",                cat: "home" },
  { en: "bathroom",                     th: "hong nam",                 cat: "home" },
  { en: "kitchen",                      th: "khrua",                    cat: "home" },
  { en: "living room",                  th: "hong nang len",            cat: "home" },
  { en: "door",                         th: "pra-too",                  cat: "home" },
  { en: "window",                       th: "na-tang",                  cat: "home" },
  { en: "table",                        th: "toh",                      cat: "home" },
  { en: "chair",                        th: "gao-ee",                   cat: "home" },
  { en: "bed",                          th: "tiang",                    cat: "home" },
  { en: "pillow",                       th: "morn",                     cat: "home" },
  { en: "air conditioning",             th: "ea",                       cat: "home" },
  { en: "fan",                          th: "phat lom",                 cat: "home" },
  { en: "television",                   th: "tho-ra-that",              cat: "home" },
  { en: "refrigerator",                 th: "too yen",                  cat: "home" },

  // ── Verbs (80) ──
  { en: "eat",                          th: "kin",                      cat: "verbs" },
  { en: "drink",                        th: "deum",                     cat: "verbs" },
  { en: "sleep",                        th: "norn",                     cat: "verbs" },
  { en: "wake up",                      th: "teun",                     cat: "verbs" },
  { en: "go",                           th: "pai",                      cat: "verbs" },
  { en: "come",                         th: "ma",                       cat: "verbs", note: "mid tone; same syllable as dog (falling) and horse (rising)" },
  { en: "want",                         th: "ao / yaak",                cat: "verbs", note: "ao = colloquial 'want/take'; yaak = to want/wish (more formal)" },
  { en: "don't want",                   th: "mai ao",                   cat: "verbs" },
  { en: "like",                         th: "chob",                     cat: "verbs" },
  { en: "love",                         th: "rak",                      cat: "verbs" },
  { en: "hate",                         th: "gliat",                    cat: "verbs" },
  { en: "see",                          th: "hen",                      cat: "verbs" },
  { en: "look / watch",                 th: "doo",                      cat: "verbs" },
  { en: "listen",                       th: "fang",                     cat: "verbs" },
  { en: "speak / talk",                 th: "poot",                     cat: "verbs" },
  { en: "read",                         th: "an",                       cat: "verbs" },
  { en: "write",                        th: "khian",                    cat: "verbs" },
  { en: "understand",                   th: "khao jai",                 cat: "verbs" },
  { en: "know",                         th: "roo",                      cat: "verbs" },
  { en: "think",                        th: "khit",                     cat: "verbs" },
  { en: "remember",                     th: "jam",                      cat: "verbs" },
  { en: "forget",                       th: "leum",                     cat: "verbs" },
  { en: "help",                         th: "chuay",                    cat: "verbs" },
  { en: "buy",                          th: "seu",                      cat: "verbs" },
  { en: "sell",                         th: "khai",                     cat: "verbs", note: "same romanization as egg (khai, food) — tones differ" },
  { en: "pay",                          th: "jai ngoen",                cat: "verbs" },
  { en: "have",                         th: "mee",                      cat: "verbs" },
  { en: "don't have",                   th: "mai mee",                  cat: "verbs" },
  { en: "can",                          th: "dai",                      cat: "verbs", note: "also: past tense marker placed after verb; 'to get/obtain'" },
  { en: "cannot",                       th: "mai dai",                  cat: "verbs", note: "mai = negation; dai = can; mai dai also = 'didn't' (past tense)" },
  { en: "do / make",                    th: "tham",                     cat: "verbs", note: "also means 'ask' when written differently; context clarifies" },
  { en: "stay / live",                  th: "yoo",                      cat: "verbs" },
  { en: "sit",                          th: "nang",                     cat: "verbs" },
  { en: "stand",                        th: "yeun",                     cat: "verbs" },
  { en: "walk",                         th: "dern",                     cat: "verbs" },
  { en: "run",                          th: "wing",                     cat: "verbs" },
  { en: "drive",                        th: "khap",                     cat: "verbs" },
  { en: "ride (motorbike)",             th: "khee",                     cat: "verbs" },
  { en: "fly",                          th: "bin",                      cat: "verbs" },
  { en: "swim",                         th: "way nam",                  cat: "verbs" },
  { en: "cook",                         th: "tam khrua",                cat: "verbs" },
  { en: "clean",                        th: "tham kwahm sa-aat",        cat: "verbs" },
  { en: "wash",                         th: "lang",                     cat: "verbs" },
  { en: "open",                         th: "poet",                     cat: "verbs" },
  { en: "close",                        th: "pit",                      cat: "verbs" },
  { en: "call (phone)",                 th: "tho",                      cat: "verbs" },
  { en: "send",                         th: "song",                     cat: "verbs" },
  { en: "receive",                      th: "rap",                      cat: "verbs" },
  { en: "find",                         th: "ha",                       cat: "verbs" },
  { en: "give",                         th: "hai",                      cat: "verbs" },
  { en: "take",                         th: "ao",                       cat: "verbs" },
  { en: "leave / go out",               th: "ork",                      cat: "verbs" },
  { en: "arrive",                       th: "theung",                   cat: "verbs" },
  { en: "wait",                         th: "ror",                      cat: "verbs" },
  { en: "meet",                         th: "phob",                     cat: "verbs" },
  { en: "ask",                          th: "tham",                     cat: "verbs" },
  { en: "answer",                       th: "tob",                      cat: "verbs" },
  { en: "study",                        th: "rian",                     cat: "verbs" },
  { en: "work",                         th: "tham ngan",                cat: "verbs" },
  { en: "play",                         th: "len",                      cat: "verbs" },
  { en: "sing",                         th: "rong phleng",              cat: "verbs" },
  { en: "dance",                        th: "ten",                      cat: "verbs" },
  { en: "laugh",                        th: "hua roh",                  cat: "verbs" },
  { en: "cry",                          th: "rong hai",                 cat: "verbs" },
  { en: "smile",                        th: "yim",                      cat: "verbs" },
  { en: "worry",                        th: "pen huang",                cat: "verbs" },
  { en: "hurry",                        th: "reo reo",                  cat: "verbs" },
  { en: "rest",                         th: "phak",                     cat: "verbs" },
  { en: "exercise",                     th: "ork gam lang gai",         cat: "verbs" },
  { en: "shower",                       th: "ab nam",                   cat: "verbs" },
  { en: "return",                       th: "glap",                     cat: "verbs" },
  { en: "borrow",                       th: "yaem",                     cat: "verbs" },
  { en: "try",                          th: "long / pha-ya-yam",        cat: "verbs" },
  { en: "check",                        th: "truat sob",                cat: "verbs" },
  { en: "change",                       th: "plian",                    cat: "verbs" },
  { en: "choose",                       th: "leuak",                    cat: "verbs" },
  { en: "use",                          th: "chai",                     cat: "verbs" },
  { en: "start",                        th: "rerm",                     cat: "verbs" },
  { en: "finish",                       th: "set",                      cat: "verbs" },
  { en: "lose",                         th: "hai",                      cat: "verbs" },

  // ── Adjectives (55) ──
  { en: "good",                         th: "dee",                      cat: "adjectives" },
  { en: "bad",                          th: "mai dee / chua",           cat: "adjectives" },
  { en: "beautiful",                    th: "suai",                     cat: "adjectives" },
  { en: "cute",                         th: "narak",                    cat: "adjectives" },
  { en: "big",                          th: "yai",                      cat: "adjectives" },
  { en: "small",                        th: "lek",                      cat: "adjectives" },
  { en: "tall",                         th: "soong",                    cat: "adjectives" },
  { en: "short (height)",               th: "tia",                      cat: "adjectives" },
  { en: "long",                         th: "yao",                      cat: "adjectives" },
  { en: "short (length)",               th: "san",                      cat: "adjectives" },
  { en: "wide",                         th: "gwang",                    cat: "adjectives" },
  { en: "narrow",                       th: "kaep",                     cat: "adjectives" },
  { en: "heavy",                        th: "nak",                      cat: "adjectives" },
  { en: "light (weight)",               th: "bow",                      cat: "adjectives" },
  { en: "hot",                          th: "rorn",                     cat: "adjectives" },
  { en: "cold",                         th: "yen",                      cat: "adjectives" },
  { en: "warm",                         th: "oon",                      cat: "adjectives" },
  { en: "fast",                         th: "reo",                      cat: "adjectives" },
  { en: "slow",                         th: "cha",                      cat: "adjectives" },
  { en: "easy",                         th: "ngai",                     cat: "adjectives" },
  { en: "difficult",                    th: "yaak",                     cat: "adjectives" },
  { en: "fun",                          th: "sanook",                   cat: "adjectives" },
  { en: "boring",                       th: "na beua",                  cat: "adjectives" },
  { en: "interesting",                  th: "na son jai",               cat: "adjectives" },
  { en: "tired",                        th: "neuy",                     cat: "adjectives" },
  { en: "hungry",                       th: "hiu",                      cat: "adjectives" },
  { en: "thirsty",                      th: "hiu nam",                  cat: "adjectives" },
  { en: "full (after eating)",          th: "im",                       cat: "adjectives" },
  { en: "happy",                        th: "dee jai",                  cat: "adjectives" },
  { en: "sad",                          th: "sia jai",                  cat: "adjectives" },
  { en: "angry",                        th: "grot",                     cat: "adjectives" },
  { en: "scared",                       th: "glua",                     cat: "adjectives" },
  { en: "excited",                      th: "teun ten",                 cat: "adjectives" },
  { en: "expensive",                    th: "phaeng",                   cat: "adjectives" },
  { en: "cheap",                        th: "thook",                    cat: "adjectives" },
  { en: "near",                         th: "klai",                     cat: "adjectives" },
  { en: "far",                          th: "glai",                     cat: "adjectives" },
  { en: "new",                          th: "mai",                      cat: "adjectives" },
  { en: "old",                          th: "gao",                      cat: "adjectives" },
  { en: "clean",                        th: "sa-aat",                   cat: "adjectives" },
  { en: "dirty",                        th: "sok-ga-prok",              cat: "adjectives" },
  { en: "quiet",                        th: "ngiap",                    cat: "adjectives" },
  { en: "noisy",                        th: "dang",                     cat: "adjectives" },
  { en: "safe",                         th: "phlot-pai",                cat: "adjectives" },
  { en: "dangerous",                    th: "an-ta-rai",                cat: "adjectives" },
  { en: "correct",                      th: "thook-tong",               cat: "adjectives" },
  { en: "wrong",                        th: "phit",                     cat: "adjectives" },
  { en: "same",                         th: "meuan",                    cat: "adjectives" },
  { en: "different",                    th: "tang",                     cat: "adjectives" },
  { en: "enough",                       th: "por",                      cat: "adjectives" },
  { en: "more",                         th: "ik",                       cat: "adjectives" },
  { en: "less",                         th: "noi long",                 cat: "adjectives" },
  { en: "a lot / very",                 th: "mak",                      cat: "adjectives" },
  { en: "a little",                     th: "nit noy",                  cat: "adjectives" },
  { en: "full (not empty)",             th: "tem",                      cat: "adjectives" },

  // ── Time (25) ──
  { en: "now",                          th: "tawn nee",                 cat: "time" },
  { en: "today",                        th: "wan nee",                  cat: "time" },
  { en: "tomorrow",                     th: "prung nee",                cat: "time" },
  { en: "yesterday",                    th: "meua wan",                 cat: "time" },
  { en: "day after tomorrow",           th: "ma-reun nee",              cat: "time" },
  { en: "morning",                      th: "torn chao",                cat: "time" },
  { en: "afternoon",                    th: "torn bai",                 cat: "time" },
  { en: "evening",                      th: "torn yen",                 cat: "time" },
  { en: "night",                        th: "torn keun",                cat: "time" },
  { en: "midnight",                     th: "thiang keun",              cat: "time" },
  { en: "day",                          th: "wan",                      cat: "time" },
  { en: "week",                         th: "a-thit",                   cat: "time" },
  { en: "month",                        th: "deuan",                    cat: "time" },
  { en: "year",                         th: "pee",                      cat: "time" },
  { en: "hour",                         th: "chua mong",                cat: "time" },
  { en: "minute",                       th: "na-thee",                  cat: "time" },
  { en: "early",                        th: "raeo",                     cat: "time" },
  { en: "late",                         th: "sai",                      cat: "time" },
  { en: "on time",                      th: "trong way-la",             cat: "time" },
  { en: "always",                       th: "sa-mer",                   cat: "time" },
  { en: "sometimes",                    th: "bang krang",               cat: "time" },
  { en: "never",                        th: "mai koey",                 cat: "time" },
  { en: "already",                      th: "laew",                     cat: "time" },
  { en: "not yet",                      th: "yang mai",                 cat: "time" },
  { en: "soon",                         th: "ik diaw",                  cat: "time" },

  // ── Days (7) ──
  { en: "Monday",                       th: "wan jan",                  cat: "days" },
  { en: "Tuesday",                      th: "wan ang-khan",             cat: "days" },
  { en: "Wednesday",                    th: "wan phut",                 cat: "days" },
  { en: "Thursday",                     th: "wan pha-rue-hat",          cat: "days" },
  { en: "Friday",                       th: "wan suk",                  cat: "days" },
  { en: "Saturday",                     th: "wan sao",                  cat: "days" },
  { en: "Sunday",                       th: "wan a-thit",               cat: "days" },

  // ── Months (12) ──
  { en: "January",                      th: "ma-ga-ra-khom",            cat: "months" },
  { en: "February",                     th: "gum-pha-phan",             cat: "months" },
  { en: "March",                        th: "mee-na-khom",              cat: "months" },
  { en: "April",                        th: "may-sa-yon",               cat: "months" },
  { en: "May",                          th: "phreut-sa-pha-khom",       cat: "months" },
  { en: "June",                         th: "mi-thu-na-yon",            cat: "months" },
  { en: "July",                         th: "ga-ra-ga-da-khom",         cat: "months" },
  { en: "August",                       th: "sing-ha-khom",             cat: "months" },
  { en: "September",                    th: "gan-ya-yon",               cat: "months" },
  { en: "October",                      th: "tu-la-khom",               cat: "months" },
  { en: "November",                     th: "phreut-sa-ji-ga-yon",      cat: "months" },
  { en: "December",                     th: "than-wa-khom",             cat: "months" },

  // ── Directions (10) ──
  { en: "left",                         th: "sai",                      cat: "directions" },
  { en: "right",                        th: "khwa",                     cat: "directions" },
  { en: "straight ahead",               th: "trong pai",                cat: "directions" },
  { en: "turn",                         th: "leo",                      cat: "directions" },
  { en: "north",                        th: "nuea",                     cat: "directions" },
  { en: "south",                        th: "tai",                      cat: "directions" },
  { en: "east",                         th: "tawan ork",                cat: "directions" },
  { en: "west",                         th: "tawan tok",                cat: "directions" },
  { en: "near",                         th: "klai",                     cat: "directions" },
  { en: "far",                          th: "glai",                     cat: "directions" },

  // ── Shopping (12) ──
  { en: "money",                        th: "ngoen",                    cat: "shopping" },
  { en: "baht (currency)",              th: "baht",                     cat: "shopping" },
  { en: "how much?",                    th: "tao rai",                  cat: "shopping" },
  { en: "discount",                     th: "lot ra ka",                cat: "shopping" },
  { en: "receipt",                      th: "bai set",                  cat: "shopping" },
  { en: "cash",                         th: "ngoen sot",                cat: "shopping" },
  { en: "credit card",                  th: "bat kre-dit",              cat: "shopping" },
  { en: "free (no cost)",               th: "free",                     cat: "shopping" },
  { en: "size",                         th: "kha-nat",                  cat: "shopping" },
  { en: "price",                        th: "ra-kha",                   cat: "shopping" },
  { en: "bag (shopping)",               th: "thong",                    cat: "shopping" },
  { en: "change (coins)",               th: "ngoen torn",               cat: "shopping" },

  // ── Health (20) ──
  { en: "doctor",                       th: "moh",                      cat: "health" },
  { en: "nurse",                        th: "pha-ya-ban",               cat: "health" },
  { en: "medicine",                     th: "ya",                       cat: "health" },
  { en: "sick / unwell",                th: "mai sa-bai",               cat: "health" },
  { en: "hurt / pain",                  th: "jep",                      cat: "health" },
  { en: "headache",                     th: "puad hua",                 cat: "health" },
  { en: "stomach ache",                 th: "puad thong",               cat: "health" },
  { en: "fever",                        th: "pen khai",                 cat: "health" },
  { en: "cold (illness)",               th: "pen wat",                  cat: "health" },
  { en: "cough",                        th: "ai",                       cat: "health" },
  { en: "allergy",                      th: "phaeng",                   cat: "health" },
  { en: "emergency",                    th: "chuak-chern",              cat: "health" },
  { en: "ambulance",                    th: "rot pha-ya-ban",           cat: "health" },
  { en: "blood",                        th: "leuad",                    cat: "health" },
  { en: "dizzy",                        th: "wian hua",                 cat: "health" },
  { en: "I feel unwell",                th: "phom mai sa-bai",          cat: "health" },
  { en: "call a doctor",                th: "riak moh",                 cat: "health" },
  { en: "pharmacy",                     th: "raan khai ya",             cat: "health" },
  { en: "tired / exhausted",            th: "neuy",                     cat: "health" },
  { en: "broken / injured",             th: "hak / bat jep",           cat: "health" },

  // ── Emotions (15) ──
  { en: "happy",                        th: "dee jai",                  cat: "emotions" },
  { en: "sad",                          th: "sia jai",                  cat: "emotions" },
  { en: "angry",                        th: "grot",                     cat: "emotions" },
  { en: "scared",                       th: "glua",                     cat: "emotions" },
  { en: "lonely",                       th: "ngao",                     cat: "emotions" },
  { en: "stressed",                     th: "khriat",                   cat: "emotions" },
  { en: "relaxed",                      th: "sa-bai jai",               cat: "emotions" },
  { en: "proud",                        th: "pa-oom jai",               cat: "emotions" },
  { en: "embarrassed",                  th: "a-y",                      cat: "emotions" },
  { en: "jealous",                      th: "it-cha",                   cat: "emotions" },
  { en: "confused",                     th: "ngong",                    cat: "emotions" },
  { en: "excited",                      th: "teun ten",                 cat: "emotions" },
  { en: "nervous",                      th: "neua non mai yu",          cat: "emotions" },
  { en: "grateful",                     th: "kob jai",                  cat: "emotions" },
  { en: "bored",                        th: "beua",                     cat: "emotions" },

  // ── Work & school (20) ──
  { en: "work",                         th: "tham ngan",                cat: "work" },
  { en: "job / career",                 th: "a-cheep",                  cat: "work" },
  { en: "boss",                         th: "jao nai",                  cat: "work" },
  { en: "colleague",                    th: "pheuan ruam ngan",         cat: "work" },
  { en: "meeting",                      th: "pra-chum",                 cat: "work" },
  { en: "computer",                     th: "khom-phiu-ter",            cat: "work" },
  { en: "phone",                        th: "tho-ra-sap",               cat: "work" },
  { en: "email",                        th: "ee-mel",                   cat: "work" },
  { en: "school",                       th: "rong rian",                cat: "work" },
  { en: "teacher",                      th: "khruu",                    cat: "work" },
  { en: "student",                      th: "nak rian",                 cat: "work" },
  { en: "homework",                     th: "gan ban",                  cat: "work" },
  { en: "exam / test",                  th: "sob",                      cat: "work" },
  { en: "pass",                         th: "phan",                     cat: "work" },
  { en: "fail",                         th: "tok",                      cat: "work" },
  { en: "salary",                       th: "ngoen deuan",              cat: "work" },
  { en: "holiday / day off",            th: "wan yut",                  cat: "work" },
  { en: "busy",                         th: "yung",                     cat: "work" },
  { en: "free (not busy)",              th: "wang",                     cat: "work" },
  { en: "project",                      th: "krong-gaan",               cat: "work" },
];
